### ISSUE TITLE
Use of $XDG_RUNTIME_DIR breaks macOS support

### ISSUE THREAD

**Issue by jaminthorns** [acomagu/fish-async-prompt#47]
In the script, the `$XDG_RUNTIME_DIR` environment variable is used, which is part of the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). macOS does not implement this standard. Since `$XDG_RUNTIME_DIR` will expand to an empty string, the script tries to write to `/fish-async-prompt`. In macOS Big Sur, the root directory is read-only, which renders this plugin non-functional.

**Comment by acomagu** [comment]
@jaminthorns Oh, sorry for that. I think the master is fixed by 40f30a4. Could you retry?

**Comment by lordyod** [comment]
Hi, I think https://github.com/acomagu/fish-async-prompt/commit/40f30a4048b81f03fa871942dcb1671ea0fe7a53 is in master, right? Because this still fails on login:

```
mkdir: /run/user/501/fish-async-prompt: Read-only file system
```
